# Generated by Django 5.1.7 on 2025-04-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfile',
            name='file',
        ),
    ]
