# Generated by Django 5.1.7 on 2025-03-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_country_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='device',
            table='User devices',
        ),
    ]
